/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCompetitorsRouteImport } from './routes/api/competitors'
import { Route as ApiDecisionsRouteImport } from './routes/api/decisions'
import { Route as ApiDemoRouteImport } from './routes/api/demo'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiMemoriesRouteImport } from './routes/api/memories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorsRoute = ApiCompetitorsRouteImport.update({
  id: '/api/competitors',
  path: '/api/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecisionsRoute = ApiDecisionsRouteImport.update({
  id: '/api/decisions',
  path: '/api/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoriesRoute = ApiMemoriesRouteImport.update({
  id: '/api/memories',
  path: '/api/memories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/competitors': typeof CompetitorsRoute
  '/decisions': typeof DecisionsRoute
  '/feedback': typeof FeedbackRoute
  '/meetings': typeof MeetingsRoute
  '/memory': typeof MemoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/competitors': typeof ApiCompetitorsRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/memories': typeof ApiMemoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/competitors': typeof CompetitorsRoute
  '/decisions': typeof DecisionsRoute
  '/feedback': typeof FeedbackRoute
  '/meetings': typeof MeetingsRoute
  '/memory': typeof MemoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/competitors': typeof ApiCompetitorsRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/memories': typeof ApiMemoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/competitors': typeof CompetitorsRoute
  '/decisions': typeof DecisionsRoute
  '/feedback': typeof FeedbackRoute
  '/meetings': typeof MeetingsRoute
  '/memory': typeof MemoryRoute
  '/api/chat': typeof ApiChatRoute
  '/api/competitors': typeof ApiCompetitorsRoute
  '/api/decisions': typeof ApiDecisionsRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/memories': typeof ApiMemoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/competitors'
    | '/decisions'
    | '/feedback'
    | '/meetings'
    | '/memory'
    | '/api/chat'
    | '/api/competitors'
    | '/api/decisions'
    | '/api/demo'
    | '/api/feedback'
    | '/api/health'
    | '/api/meetings'
    | '/api/memories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/competitors'
    | '/decisions'
    | '/feedback'
    | '/meetings'
    | '/memory'
    | '/api/chat'
    | '/api/competitors'
    | '/api/decisions'
    | '/api/demo'
    | '/api/feedback'
    | '/api/health'
    | '/api/meetings'
    | '/api/memories'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/competitors'
    | '/decisions'
    | '/feedback'
    | '/meetings'
    | '/memory'
    | '/api/chat'
    | '/api/competitors'
    | '/api/decisions'
    | '/api/demo'
    | '/api/feedback'
    | '/api/health'
    | '/api/meetings'
    | '/api/memories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  CompetitorsRoute: typeof CompetitorsRoute
  DecisionsRoute: typeof DecisionsRoute
  FeedbackRoute: typeof FeedbackRoute
  MeetingsRoute: typeof MeetingsRoute
  MemoryRoute: typeof MemoryRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCompetitorsRoute: typeof ApiCompetitorsRoute
  ApiDecisionsRoute: typeof ApiDecisionsRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiMemoriesRoute: typeof ApiMemoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitors': {
      id: '/api/competitors'
      path: '/api/competitors'
      fullPath: '/api/competitors'
      preLoaderRoute: typeof ApiCompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decisions': {
      id: '/api/decisions'
      path: '/api/decisions'
      fullPath: '/api/decisions'
      preLoaderRoute: typeof ApiDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memories': {
      id: '/api/memories'
      path: '/api/memories'
      fullPath: '/api/memories'
      preLoaderRoute: typeof ApiMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  CompetitorsRoute: CompetitorsRoute,
  DecisionsRoute: DecisionsRoute,
  FeedbackRoute: FeedbackRoute,
  MeetingsRoute: MeetingsRoute,
  MemoryRoute: MemoryRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCompetitorsRoute: ApiCompetitorsRoute,
  ApiDecisionsRoute: ApiDecisionsRoute,
  ApiDemoRoute: ApiDemoRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiMemoriesRoute: ApiMemoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
